using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("ReadyM.Relay.Client")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Web")]
[assembly: InternalsVisibleTo("ReadyM.Sdk.Serverside")]
[assembly: InternalsVisibleTo("ReadyM.Sdk.V1.Serverside")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server.PluginHost")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server.Wukong")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server.Oblivion")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Tests")]
[assembly: InternalsVisibleTo("ReadyM.Wukong.Common")]
[assembly: InternalsVisibleTo("WukongMp.Api")]
[assembly: InternalsVisibleTo("OblivionMpCSharpMod")]
[assembly: InternalsVisibleTo("ReadyM.Sdk.Common")]
[assembly: InternalsVisibleTo("ReadyM.Sdk.V1.Client")]
[assembly: InternalsVisibleTo("WukongMp.Sdk")]
[assembly: InternalsVisibleTo("OblivionMp.Sdk.Client")]
[assembly: InternalsVisibleTo("OblivionMp.Sdk.V1.Client")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Common.Oblivion")] // TODO: Change name to ReadyM.Oblivion.Common