<?xml version="1.0" encoding="utf-8"?>

<Project>
    <PropertyGroup>
        <ParentBuildTargets>$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))</ParentBuildTargets>
    </PropertyGroup>
    <Import Project="$(ParentBuildTargets)" Condition="'$(ParentBuildTargets)' != ''" />

    <Import Project="$(MSBuildThisFileDirectory)ReadyM.Layering.targets" Condition="'$(ReadyMLayeringImported)' != 'true'" />
</Project>
